version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dsauser
      POSTGRES_PASSWORD: dsapass
      POSTGRES_DB: dsadb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    command: ./start.sh
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: postgresql+psycopg2://dsauser:dsapass@db:5432/dsadb
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: 