"""add_user_preferences

Revision ID: 1e624225a14a
Revises: 40cba1ae9ee3
Create Date: 2025-07-24 08:42:12.803178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e624225a14a'
down_revision: Union[str, Sequence[str], None] = '40cba1ae9ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('font_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'font_size')
    op.drop_column('users', 'theme_preference')
    # ### end Alembic commands ###
